feat(button): added icon support
stardust-ui/react-old pull request #111
Opened 2018-07-18 15:31 UTC by Bugaa92

# Button

A standard button.

### TODO

- [x] Conformance test
- [x] Minimal doc site example
- [ ] Stardust base theme
- [x] Teams Light theme
- [ ] Teams Dark theme
- [ ] Teams Contrast theme
- [ ] Confirm RTL usage
- [ ] [W3 accessibility](https://www.w3.org/standards/webdesign/accessibility) check
- [ ] [Stardust accessibility](https://github.com/stardust-ui/accessibility) check
- [ ] Update glossary props table
- [ ] Update the CHANGELOG.md

# API Proposal

## Icon

A button can be made of only an icon. 

![screen shot 2018-07-18 at 17 20 15](https://user-images.githubusercontent.com/5442794/42891229-2353aa74-8aaf-11e8-8057-e086bf4f4ce1.png)

```jsx
<Button type="primary" icon="book" />
```
will output
```html
<button>
  <i></i>
</button>
```

## Labeled Icon

A button can use an icon as a label.

![screen shot 2018-07-18 at 17 20 24](https://user-images.githubusercontent.com/5442794/42891552-efc4b184-8aaf-11e8-82c4-18d303e00f3e.png)

```jsx
<Button type="primary" icon="book" content="Click me left" iconPosition="left" />
<Button type="secondary" icon="coffee" content="Click me right" iconPosition="right" />
```
will output
```html
<button>
  <i></i>
  <span>Click me left</span>
</button>
<button>
  <span>Click me right</span>
  <i></i>
</button>
```

## Circular Emphasis

A button can be circular and formatted to show different levels of emphasis.

![screen shot 2018-07-18 at 17 21 09](https://user-images.githubusercontent.com/5442794/42891662-32631634-8ab0-11e8-9153-5be4dd4820ab.png)

```jsx
<Button type="primary" circular icon="coffee" />
<Button type="secondary" circular icon="book" />
```
will output
```html
<button>
  <i></i>
</button>
<button>
  <i></i>
</button>
```

2018-07-18 16:26 UTC, bmdalex commented
ready for review
@levithomason 
@mnajdova 
@kuzhelov

2018-07-19 05:58 UTC, levithomason requested changes
I didn't quite finish getting through the components. I will do so tomorrow. Here are some comments for now.

2018-07-19 05:58 UTC, levithomason commented on CHANGELOG.md
> +- Add Icon Button component @Bugaa92 ([#111](https://github.com/stardust-ui/react/pull/111))
Suggest "Add icon prop to the Button component". Some libraries have actual IconButton components.

2018-07-19 05:58 UTC, levithomason commented on docs/src/examples/components/Button/Types/ButtonExampleIcon.tsx
> +    <Icon name="book" color="white" style={{ margin: 'auto' }} />
No inline styles in doc examples please. Let's show exactly what the components do.

2018-07-19 05:58 UTC, levithomason commented on docs/src/examples/components/Button/Types/ButtonExampleLabeledIcon.shorthand.tsx
> +const ButtonExampleLabeledIcon = () => (
Labeled icon means something different in Semantic, suggest calling this "Icon and Content". Buttons can have labels and they can style the icon as a label resulting in a "labeled icon button". We can save that for another discussion and PR.

2018-07-19 05:58 UTC, levithomason commented on docs/src/examples/components/Button/Types/ButtonExampleLabeledIcon.tsx
> +      <Icon name="coffee" style={{ margin: 'auto' }} />
Reminder, no inline styles.

2018-07-19 05:58 UTC, levithomason commented on docs/src/examples/components/Button/Types/index.tsx
> +      description="A standard button."
We should standardize these. I'd propose "default", but would like to hear what the rest of the team thinks.

2018-07-19 05:58 UTC, levithomason commented on src/components/Button/Button.tsx
> +      PropTypes.bool,
Boolean might be cruft here.

2018-07-20 13:06 UTC, kuzhelov commented on docs/src/examples/components/Button/Types/index.tsx
> +      description="A standard button."
my vote is for `default`

2018-07-20 14:16 UTC, kuzhelov commented on docs/src/examples/components/Button/Types/ButtonExampleIcon.tsx
> +    <Icon name="book" color="white" style={{ margin: 'auto' }} />
here is a problem with that - this is file that corresponds to `Children API` case. In other words, it is where `Button` component is unaware of its children and, thus, in contrast to shorthand case, cannot introduce any appropriate styles to provide a nice look.

At the same time, we would like the presentation of both Shorthand and Children API cases being consistent with each other, so that Button's look won't suddenly change when user is switching between them for the same example (or do we?). In this case it seems that there are no other means to make these looks consistent other than introducing inline styles.

Another possible option for us could be to remove `Children API` for this example.

@levithomason, please, let us know about your thoughts.

2018-07-20 15:33 UTC, kuzhelov commented
>> No inline styles in doc examples please. Let's show exactly what the components do.

here is a problem with that - this is file that corresponds to `Children API` case. In other words, it is where `Button` component is unaware of its children and, thus, in contrast to shorthand case, cannot introduce any appropriate styles to provide a nice look.

At the same time, we would like the presentation of both Shorthand and `Children API` cases being consistent with each other, so that `Button's` look won't suddenly change when user is switching between them for the same example (or do we?). In this case it seems that there are no other means to make these looks consistent other than introducing inline styles.

Another possible option for us could be to remove `Children API` for this example.

@levithomason, please, let us know about your thoughts.

2018-07-24 11:28 UTC, bmdalex commented on docs/src/examples/components/Button/Types/ButtonExampleIcon.tsx
> +    <Icon name="book" color="white" style={{ margin: 'auto' }} />
@kuzhelov thanks for detailing the reasons for making the style changes in example;
@levithomason Roman explained very well why inline styles were added, what are your thoughts?

2018-07-25 16:01 UTC, Bugaa92 commented
Moved to new repo: [stardust-ui/react/pull/13](https://github.com/stardust-ui/react/pull/13)

2018-07-25 16:01 UTC, closed without merging