Base icon component
stardust-ui/react-old pull request #17
Opened 2018-06-13 23:59 UTC by WrathOfZombies

- [x] Port base component
- [ ] Add custom prop types & docs
- [ ] Add examples
- [ ] Add variants & knobs

2018-06-14 10:19 UTC, levithomason commented on src/components/Icon/Icon.js
> +    // )
Safe to delete all the cruft here.  We'll reimplement what we need as we need it.

2018-06-14 10:19 UTC, levithomason commented on src/components/Icon/Icon.js
> +    'aria-label': PropTypes.string,
Let's strip propTypes down to only what this PR will add.  Preferably, the bare minimum needed to render the default example.  Probably the `name` prop?

We'll add props and examples as we need them.

2018-06-21 00:08 UTC, levithomason requested changes
Let's split a PR out from here that implements only the default icon example.  There's a bit too much to review effectively in this PR.

Ideally, the first PR will only be the base implementation.  Then, each prop/feature will be added as needed.

2018-06-26 15:27 UTC, kuzhelov commented
taking this PR to split it on two different ones

2018-08-06 15:59 UTC, levithomason commented
See the new repo Icon.  We've trimmed it down and updated it there for our initial needs.

https://github.com/stardust-ui/react

2018-08-06 15:59 UTC, closed without merging