Replacing rem utility with pxToRem
stardust-ui/react-old pull request #44
Opened 2018-06-29 16:10 UTC by seankeating

Simplifying the Rem utility to take in px value instead of a font-size based 10 REM value.
Updating code to utility class using TypeScript.

2018-06-30 16:24 UTC, seankeating commented on src/components/Divider/dividerRules.ts
> +    marginTop: pxToRem(10 + size * 7.5),
@levithomason - The resulting values seem to be off here.  Can you validate?

2018-07-03 18:50 UTC, davezuko commented on src/lib/fontSizeUtility.ts
> +class FontSizeUtility {
I'd vote for avoiding classes as much as possible, especially for general utilities. TypeScript, with all of its benefits, can sometimes encourage too much abstraction, so we need to be extra conscious of our patterns if we want to keep things simple.

In a case like this, the public API is a set of standalone functions, and so there isn't any need to define them as part of a singleton. Writing pure functions will help keep them small and maintainable, especially since there isn't any possibility of shared state.

I'd suggest rewriting this to get rid of the class, and export the public functions directly. You can still get all the benefits of private variables by defining, but not exporting, them within the module.

2018-07-03 18:59 UTC, dvdzkwsk requested changes
Changes look good. Only blocker is the de-class-ification of the font size utility.

2018-07-03 21:07 UTC, seankeating commented on src/lib/fontSizeUtility.ts
> +class FontSizeUtility {
👍

2018-07-04 01:30 UTC, merged