Cleanup
stardust-ui/react-old pull request #72
Opened 2018-07-11 19:05 UTC by seankeating

Updating paths relative to root.
Updated comment in fontSizeUtility.ts.
Removed old JS test file.

2018-07-12 00:39 UTC, levithomason commented
I think we should keep our src directory simple paths so consumers can compile it without having special cased handling.

We do allow root require from within docs and in tests, but I've been thinking the confusion of where you can and can't safely do so might not be worth it.  Proposing we nix the root require altogether as most editors handle resolution and path finding automatically for devs.  This makes our code less magical and more portable.

Thoughts?

2018-07-12 16:25 UTC, seankeating commented
@levithomason - I agree.  If we cannot guarantee that the developers consuming our product cannot expect the same environment, i.e. root based requires, and we cannot provide it automatically for them, then we shouldn't use it ourselves.

2018-07-12 18:53 UTC, levithomason commented
Cool, then let's make this PR into a chore to remove the root require helpers instead.

2018-07-19 00:55 UTC, levithomason requested changes

2018-07-19 00:55 UTC, levithomason commented on build/tsconfig.common.json
> +      "*": ["../*", "../types/*"]
This seems to still allow these root style imports from within the `src` directory:

```
import { customPropTypes, UIComponent } from 'src/lib'
```

We want to prevent devs from accidentally importing from the root and ensure they use relative paths instead.

2018-07-19 00:58 UTC, levithomason commented on build/tsconfig.common.json
> +      "*": ["../*", "../types/*"]
This is probably due to the webpack config:

```
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json'],
    alias: {
      '@stardust-ui/react': paths.src(),
      src: paths.src(),
      docs: paths.base('docs'),
      'package.json': paths.base('package.json'),
    },
  },
```

The webpack config is used to package and build the doc site.  Since that is also the dev environment, src code gets resolved correctly even if it uses root level imports due to webpack.

I think we may need to just drop the webpack alias config also and require that all imports be relative.

2021-05-26 19:43 UTC, closed without merging