chore: Remove vscode specific config, ignore .vscode folder
stardust-ui/react-old pull request #94
Opened 2018-07-16 20:58 UTC by seankeating

Remove vscode specific config, ignore .vscode folder

2018-07-16 21:01 UTC, levithomason requested changes

2018-07-16 21:01 UTC, levithomason commented on .gitignore
> +vscode/
Missing a dot here: `.vscode`

2018-07-16 21:20 UTC, dzearing commented on .gitignore
> +.vscode/
Why remove .vscode? There are some nice things that are valuable to check in. 

Examples:

Build script helpers for debugging tests - in Fabric, we have a monorepo with many packages, so we wrote a script that identifies the file you're looking at and walks up the tree looking for the nearest jest.config folder to run tests from within. This way devs can just put a breakpoint in any test file in any package and press f5 to debug it.

Default rules about formatting (use spaces, format on save, etc), though much of this can be controlled by Prettier.

Recommended extensions for the repo.

2018-07-17 18:08 UTC, seankeating commented on .gitignore
> +.vscode/
Current recommendation is to have no IDE specific code in the repo.
@levithomason to comment.

2018-07-17 18:35 UTC, levithomason commented on .gitignore
> +.vscode/
Not everyone uses vscode.  This is an open source project and needs to support all developers.  We won't be committing any code editor specific code.  At best, we may include an [editorconfig](https://editorconfig.org/) file but we use prettier so most of that is not needed either.

2018-07-17 18:35 UTC, levithomason approved these changes

2018-07-17 21:18 UTC, merged